### ISSUE TITLE
Dockerize Project

### ISSUE THREAD

**Issue by cfahlgren1** [cfahlgren1/Bounce#12]
Dockerize the application so that it is easy to setup environment and tests without hassles of dependencies

**Comment by ghost** [comment]
I think that's an amazing idea! Will be much easier for people who want to contribute. Not familiar with Docker though so can't help much, but I'll be happy to be able to use it!

**Comment by moohco** [comment]
looking into this currently, its been a while since i dockerized a Django app :)

**Comment by cfahlgren1** [comment]
> looking into this currently, its been a while since i dockerized a Django app :)

Yes, the environment setup closely follows this guide if that helps. The main thing is having the GeoDjango libraries and postgres database in Docker. I will be adding a Contributing file with environment setup documentation. But if we can dockerize before then, even better.
https://realpython.com/location-based-app-with-geodjango-tutorial/

**Comment by marcorichetta** [comment]
Last night I fought with docker and postgis but at the end I was able to configure the project, run the migrations and see the site on the browser. 

It's not the perfect solution but at least it's an initial one. I'll upload it when I get back to the computer. 

@cfahlgren1 

- a  `.env.template` file would be super useful.

- Also instructions on how to populate the DB. What does `populate.py` do?

**Comment by cfahlgren1** [comment]
> Last night I fought with docker and postgis but at the end I was able to configure the project, run the migrations and see the site on the browser.
> 
> It's not the perfect solution but at least it's an initial one. I'll upload it when I get back to the computer.
> 
> @cfahlgren1
> 
> * a  `.env.template` file would be super useful.
> * Also instructions on how to populate the DB. What does `populate.py` do?


Awesome, I am glad you got it working. I am actively working on creating a comprehensive project setup guide for contributing right now. I am glad you got something working! Ill add an environment template file in the next hour. As for populating the DB, I will have to add some initial models to load into the db. The populate.py is what I used previously to manually add courts to the database from openstreetmaps and I forgot to remove it. So disregard that file.

**Comment by cfahlgren1** [comment]
If you want to run some test data, use the GraphQL endpoint at bouncemap.com/graphql to get a few courts that you can load into the database. This can be the temporary solution

**Comment by marcorichetta** [comment]
> If you want to run some test data, use the GraphQL endpoint at bouncemap.com/graphql to get a few courts that you can load into the database. This can be the temporary solution

Tried to run some queries like `allBasketballCourts` but I get an error because I'm not authenticated.
```json
{
  "errors": [
    {
      "message": "Not logged in!",
      "locations": [
        {
          "line": 33,
          "column": 3
        }
      ],
      "path": [
        "allBasketballCourts"
      ]
    }
  ],
  "data": {
    "allBasketballCourts": null
  }
}
```

**Comment by cfahlgren1** [comment]
> > If you want to run some test data, use the GraphQL endpoint at bouncemap.com/graphql to get a few courts that you can load into the database. This can be the temporary solution
> 
> Tried to run some queries like `allBasketballCourts` but I get an error because I'm not authenticated.
> 
> ```json
> {
>   "errors": [
>     {
>       "message": "Not logged in!",
>       "locations": [
>         {
>           "line": 33,
>           "column": 3
>         }
>       ],
>       "path": [
>         "allBasketballCourts"
>       ]
>     }
>   ],
>   "data": {
>     "allBasketballCourts": null
>   }
> }
> ```
It should work if you try now, thank you for letting me know. I removed the permissions required for the endpoint!

**Comment by cfahlgren1** [comment]
@marcorichetta I am able to compose and build the docker environment without errors except for "web_1 : no destination" and I am not able to visit the frontend. I am sure it is something simple. Once the docker is working, I just need to integrate it with Heroku so it can be deployed with docker and test to make sure the database models work correctly. What do you think the error is?

**Comment by akhmaos** [comment]
If no one has done it yet, I can do it. Dockerized a lot of applications

**Comment by cfahlgren1** [comment]
> If no one has done it yet, I can do it. Dockerized a lot of applications
@marcorichetta has a PR open at #14 with an almost perfect solution. It is almost finished, just needs a few changes.

**Comment by marcorichetta** [comment]
@cfahlgren1 Sorry for the delay. Tonight I'll try the suggestions you made and I'll finish the PR, to have an initial docker setup.
It's by no means a perfect solution haha It surely can be optimized.

**Comment by cfahlgren1** [comment]
> @cfahlgren1 Sorry for the delay. Tonight I'll try the suggestions you made and I'll finish the PR, to have an initial docker setup.
> It's by no means a perfect solution haha It surely can be optimized.

@marcorichetta No worries, once we get that merged, I will try and get started on deploying through docker on Heroku.
