### ISSUE TITLE
Integrity error caused by duplicate signup email

### ISSUE THREAD

**Issue by marcorichetta** [cfahlgren1/Bounce#16]
Just tried to enter the same email twice and got this error.
![imagen](https://user-images.githubusercontent.com/19599150/95004547-df1dd280-05c2-11eb-9273-670ca2cef8ab.png)

This error should be kept in the `home` view using `EmailSignupForm`.
The form is not valid if the email already exists in the database.

**Comment by cfahlgren1** [comment]
Handled this in [commit](https://github.com/cfahlgren1/Bounce/commit/fad106e5fa9e2fd3ec576085f0dd3612db5a80ed), it is handled in view. Further logic can be added to notify user that the email was already submitted.

**Comment by marcorichetta** [comment]
> Further logic can be added to notify user that the email was already submitted.

You can accomplish this without much hassle!
Using the form `is_valid()` method you can check for any errors (Like the already existent email), and render the same page but this time including the error for the user to see.

Look at this simple example: https://www.dark-hamster.com/application/how-to-display-form-error-in-django/
