### ISSUE TITLE
Error pages not showing correctly on live website

### ISSUE THREAD

**Issue by z-siddiqi** [cfahlgren1/Bounce#26]
I was checking the custom error pages on the live website, and to my surprise got the Django error page instead (see image). Production settings seem to have DEBUG=False so not really sure why this happens.

![Screenshot from 2020-10-22 18-38-47](https://user-images.githubusercontent.com/57043176/96910682-c30da280-1497-11eb-824c-4996e07795e3.png)

**Comment by cfahlgren1** [comment]
> I was checking the custom error pages on the live website, and to my surprise got the Django error page instead (see image). Production settings seem to have DEBUG=False so not really sure why this happens.
> 
> 
> 
> ![Screenshot from 2020-10-22 18-38-47](https://user-images.githubusercontent.com/57043176/96910682-c30da280-1497-11eb-824c-4996e07795e3.png)
> 
> 

Yes, there was an issue with the productions settings where there was a duplicate `DEBUG = True`. It has since been fixed, however, the live site hasn't been setup with the new docker deployment process since we are thinking of migrating it from Heroku to Digital Ocean.

**Comment by z-siddiqi** [comment]
> > I was checking the custom error pages on the live website, and to my surprise got the Django error page instead (see image). Production settings seem to have DEBUG=False so not really sure why this happens.
> > ![Screenshot from 2020-10-22 18-38-47](https://user-images.githubusercontent.com/57043176/96910682-c30da280-1497-11eb-824c-4996e07795e3.png)
> 
> Yes, there was an issue with the productions settings where there was a duplicate `DEBUG = True`. It has since been fixed, however, the live site hasn't been setup with the new docker deployment process since we are thinking of migrating it from Heroku to Digital Ocean.

That makes sense, thanks for explaining.
