### ISSUE TITLE
Missing handler404 view

### ISSUE THREAD

**Issue by z-siddiqi** [cfahlgren1/Bounce#27]
I noticed there is no handler404 view and would like to add that if it's okay? There are multiple 404 templates so would need clarification on which to use.

**Comment by cfahlgren1** [comment]
@z-siddiqi , sorry for the late response, I have had a really busy two weeks. Yes, feel free to add this. There's already some templates in the templates directory for a 404 page, it just needs the handler404. So go ahead :)
