### ISSUE TITLE
Slack link is not valid anymore

### ISSUE THREAD

**Issue by s-maibuecher** [cfahlgren1/Bounce#28]
Hi, saw your Reddit link and I'm interested in contributing. But there where no activities in the last three weeks. Everything fine? Your Slack channel invitation also seems to be expired.
Have a nice weekend.

**Comment by cfahlgren1** [comment]
Hey @s-maibuecher , yes, we are actually working on decoupling the backend and front end and migrating the codebase to Digital Ocean. I have had some job interviews recently that I finished so I haven't been as active as usual. But I know @johnckealy has already rewritten the basics of the front end in Vue.js and I will be working on the backend. There will be alot of areas for contributing. Here is the updated  [Slack Link](https://join.slack.com/t/bounce-gfv9723/shared_invite/zt-j3nlrdep-m1lktvK9vHS3479hEkAVcw)
