### ISSUE TITLE
Create Project Setup Guide for Contributors

### ISSUE THREAD

**Issue by cfahlgren1** [cfahlgren1/Bounce#9]
Creating a project markdown file outlining how to install and setup Django project to successfully contribute

**Comment by ngc2392** [comment]
Currently going through the process of setting the project up and am documenting my process. You can assign this to me.

**Comment by cfahlgren1** [comment]
Sounds great, I appreciate the help, make sure you are on the postgis branch.

**Comment by cfahlgren1** [comment]
> Currently going through the process of setting the project up and am documenting my process. You can assign this to me.

For your help, the project closely follows the setup guide here: https://realpython.com/location-based-app-with-geodjango-tutorial/. I plan to upload a basic contributing file that you can add to.

**Comment by ngc2392** [comment]
Thanks, that link will make it easier to get the GEO libraries set up. Do you still want this set up guide since it is currently being put into a Docker container and that will allow the set up process to be only a few commands?

**Comment by cfahlgren1** [comment]
> Thanks, that link will make it easier to get the GEO libraries set up. Do you still want this set up guide since it is currently being put into a Docker container and that will allow the set up process to be only a few commands?

Yes, I will close this issue since docker will cover it mainly. Thanks!
